spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: orlando
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  #sql.init.mode: always